cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "code/core",
  "code/cli",
  "code/gui_gtk",
  "code/gui_iced",
]

[profile.dev]
opt-level = 2
overflow-checks = true
debug-assertions = true
panic = "abort"
debug = false
codegen-units = 8
lto = false
incremental = true
# All dependencies (but not this crate itself)
[profile.dev.overrides."*"]
opt-level = 3
[profile.dev.overrides."secalc_core"]
opt-level = 2
[profile.dev.overrides."secalc_cli"]
opt-level = 2
[profile.dev.overrides."secalc_gui_gtk"]
opt-level = 2
[profile.dev.overrides."secalc_gui_iced"]
opt-level = 2

[profile.debuginfo]
inherits = 'dev'
debug = true

[profile.release]
opt-level = 's'
overflow-checks = false
debug-assertions = false
lto = true
debug = false
