[package]
name = "secalc_core"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"

[dependencies]
snafu = "0.6"
walkdir = "2.2"
roxmltree = "0.7"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
