[package]
name = "secalc_cli"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"

[dependencies]
secalc_core = { path = "../core" }
snafu = "0.6"
serde = {version = "1.0"}
serde_json = "1.0"
structopt = "0.3"

[target.'cfg(windows)'.dependencies]
winreg = "0.6"
