[package]
name = "secalc_cli"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"

[dependencies]
secalc_core = { path = "../core", features = ["extract"] }
structopt = "0.3"
steamlocate = "1"
ron = "0.7"
